name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.9
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: Run linters
  #       run: |
  #         # Run flake8 for Python code style checks
  #         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  #         # Run black for code formatting
  #         black --check .

  test:
    runs-on: ubuntu-latest
    # needs: lint

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3 
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Run tests
    - name: Run tests
      run: |
        python -m pytest tests/

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: recipe-chatbot:latest
          outputs: type=docker, dtest=/tmp/recipe-chatbot.tar
          cache-from: type=gha
          cache-to: type=gha, mode=max
      - name: Test Docker image
        run: |
          docker load -i /tmp/recipe-chatbot.tar
          docker run --rm recipe-chatbot python -c "print('Docker image is working!')"